# Generated by Django 5.2.7 on 2025-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('dateAnniversaire', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
    ]
