# Generated by Django 5.2.7 on 2025-10-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nom',
        ),
        migrations.CreateModel(
            name='DossierSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('medecin_traitant', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_sante', to='home.users')),
            ],
        ),
    ]
