# Generated by Django 5.2.7 on 2025-10-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersante',
            name='department_medical',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
